-- MySQL Script generated by MySQL Workbench
-- Fri Oct  3 22:50:13 2025
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `mydb` DEFAULT CHARACTER SET utf8 ;
-- -----------------------------------------------------
-- Schema ycyw
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema ycyw
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `ycyw` DEFAULT CHARACTER SET utf8mb4 COLLATE utf8mb4_0900_ai_ci ;
USE `mydb` ;

-- -----------------------------------------------------
-- Table `mydb`.`user`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`user` (
  `iduser` BIGINT NOT NULL AUTO_INCREMENT,
  `email` VARCHAR(255) NOT NULL,
  `password_hash` VARCHAR(255) NOT NULL,
  `first_name` VARCHAR(100) NOT NULL,
  `last_name` VARCHAR(100) NOT NULL,
  `phone` VARCHAR(50) NULL,
  `created_at` TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  PRIMARY KEY (`iduser`),
  UNIQUE INDEX `email_UNIQUE` (`email` ASC) VISIBLE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`agency`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`agency` (
  `idagency` BIGINT NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(150) NOT NULL,
  `country` VARCHAR(100) NOT NULL,
  `city` VARCHAR(100) NOT NULL,
  `address` VARCHAR(255) NOT NULL,
  PRIMARY KEY (`idagency`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`vehicle_category`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`vehicle_category` (
  `idcategory` BIGINT NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(100) NOT NULL,
  PRIMARY KEY (`idcategory`),
  UNIQUE INDEX `name_UNIQUE` (`name` ASC) VISIBLE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`vehicle`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`vehicle` (
  `idvehicle` BIGINT NOT NULL AUTO_INCREMENT,
  `agency_id` BIGINT NOT NULL,
  `category_id` BIGINT NOT NULL,
  `make` VARCHAR(100) NOT NULL,
  `model` VARCHAR(100) NOT NULL,
  `model_year` YEAR NOT NULL,
  `registration_number` VARCHAR(50) NOT NULL,
  `daily_price` DECIMAL(10,2) NOT NULL,
  `status` ENUM('AVAILABLE', 'MAINTENANCE', 'RENTED') NOT NULL,
  PRIMARY KEY (`idvehicle`),
  UNIQUE INDEX `registration_number_UNIQUE` (`registration_number` ASC) VISIBLE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`reservation`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`reservation` (
  `idreservation` BIGINT NOT NULL AUTO_INCREMENT,
  `customer_id` BIGINT NOT NULL,
  `vehicle_id` BIGINT NOT NULL,
  `pickup_agency_id` BIGINT NOT NULL,
  `dropoff_agency_id` BIGINT NOT NULL,
  `start_datetime` DATETIME NOT NULL,
  `end_datetime` DATETIME NOT NULL,
  `total_price` DECIMAL(10,2) NOT NULL,
  `status` ENUM('PENDING', 'CONFIRMED', 'CANCELLED', 'COMPLETED') NOT NULL DEFAULT 'PENDING',
  `created_at` TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  PRIMARY KEY (`idreservation`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`payment`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`payment` (
  `idpayment` BIGINT NOT NULL AUTO_INCREMENT,
  `reservation_id` VARCHAR(45) NOT NULL,
  `amount` DECIMAL(10,2) NOT NULL,
  `currency` CHAR(3) NOT NULL,
  PRIMARY KEY (`idpayment`))
ENGINE = InnoDB;

USE `ycyw` ;

-- -----------------------------------------------------
-- Table `ycyw`.`user`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `ycyw`.`user` (
  `iduser` BIGINT UNSIGNED NOT NULL AUTO_INCREMENT,
  `email` VARCHAR(255) NOT NULL,
  `password_hash` VARCHAR(255) NOT NULL,
  `first_name` VARCHAR(100) NOT NULL,
  `last_name` VARCHAR(100) NOT NULL,
  `phone` VARCHAR(50) NULL DEFAULT NULL,
  `created_at` TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  PRIMARY KEY (`iduser`),
  UNIQUE INDEX `uq_user_email` (`email` ASC) VISIBLE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `ycyw`.`agency`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `ycyw`.`agency` (
  `idagency` BIGINT UNSIGNED NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(150) NOT NULL,
  `country` VARCHAR(100) NOT NULL,
  `city` VARCHAR(100) NOT NULL,
  `address` VARCHAR(255) NOT NULL,
  PRIMARY KEY (`idagency`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `ycyw`.`vehicle_category`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `ycyw`.`vehicle_category` (
  `idcategory` BIGINT UNSIGNED NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(100) NOT NULL,
  PRIMARY KEY (`idcategory`),
  UNIQUE INDEX `uq_vehicle_category_name` (`name` ASC) VISIBLE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `ycyw`.`vehicle`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `ycyw`.`vehicle` (
  `idvehicle` BIGINT UNSIGNED NOT NULL AUTO_INCREMENT,
  `agency_id` BIGINT UNSIGNED NOT NULL,
  `category_id` BIGINT UNSIGNED NOT NULL,
  `make` VARCHAR(100) NOT NULL,
  `model` VARCHAR(100) NOT NULL,
  `model_year` YEAR NOT NULL,
  `registration_number` VARCHAR(50) NOT NULL,
  `daily_price` DECIMAL(10,2) NOT NULL,
  `status` ENUM('AVAILABLE', 'MAINTENANCE', 'RENTED') NOT NULL DEFAULT 'AVAILABLE',
  PRIMARY KEY (`idvehicle`),
  UNIQUE INDEX `uq_vehicle_registration` (`registration_number` ASC) VISIBLE,
  INDEX `idx_vehicle_agency` (`agency_id` ASC) VISIBLE,
  INDEX `idx_vehicle_category` (`category_id` ASC) VISIBLE,
  CONSTRAINT `fk_vehicle_agency`
    FOREIGN KEY (`agency_id`)
    REFERENCES `ycyw`.`agency` (`idagency`)
    ON DELETE RESTRICT
    ON UPDATE RESTRICT,
  CONSTRAINT `fk_vehicle_category`
    FOREIGN KEY (`category_id`)
    REFERENCES `ycyw`.`vehicle_category` (`idcategory`)
    ON DELETE RESTRICT
    ON UPDATE RESTRICT)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `ycyw`.`reservation`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `ycyw`.`reservation` (
  `idreservation` BIGINT UNSIGNED NOT NULL AUTO_INCREMENT,
  `customer_id` BIGINT UNSIGNED NOT NULL,
  `vehicle_id` BIGINT UNSIGNED NOT NULL,
  `pickup_agency_id` BIGINT UNSIGNED NOT NULL,
  `dropoff_agency_id` BIGINT UNSIGNED NOT NULL,
  `start_datetime` DATETIME NOT NULL,
  `end_datetime` DATETIME NOT NULL,
  `total_price` DECIMAL(10,2) NOT NULL,
  `status` ENUM('PENDING', 'CONFIRMED', 'CANCELLED', 'COMPLETED') NOT NULL DEFAULT 'PENDING',
  `created_at` TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  PRIMARY KEY (`idreservation`),
  INDEX `idx_res_vehicle_dates` (`vehicle_id` ASC, `start_datetime` ASC, `end_datetime` ASC) VISIBLE,
  INDEX `idx_res_customer_created` (`customer_id` ASC, `created_at` ASC) VISIBLE,
  INDEX `idx_res_pickup` (`pickup_agency_id` ASC) VISIBLE,
  INDEX `idx_res_dropoff` (`dropoff_agency_id` ASC) VISIBLE,
  CONSTRAINT `fk_res_customer`
    FOREIGN KEY (`customer_id`)
    REFERENCES `ycyw`.`user` (`iduser`)
    ON DELETE RESTRICT
    ON UPDATE RESTRICT,
  CONSTRAINT `fk_res_vehicle`
    FOREIGN KEY (`vehicle_id`)
    REFERENCES `ycyw`.`vehicle` (`idvehicle`)
    ON DELETE RESTRICT
    ON UPDATE RESTRICT,
  CONSTRAINT `fk_res_pickup`
    FOREIGN KEY (`pickup_agency_id`)
    REFERENCES `ycyw`.`agency` (`idagency`)
    ON DELETE RESTRICT
    ON UPDATE RESTRICT,
  CONSTRAINT `fk_res_dropoff`
    FOREIGN KEY (`dropoff_agency_id`)
    REFERENCES `ycyw`.`agency` (`idagency`)
    ON DELETE RESTRICT
    ON UPDATE RESTRICT)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `ycyw`.`payment`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `ycyw`.`payment` (
  `idpayment` BIGINT UNSIGNED NOT NULL AUTO_INCREMENT,
  `reservation_id` BIGINT UNSIGNED NOT NULL,
  `amount` DECIMAL(10,2) NOT NULL,
  `currency` CHAR(3) NOT NULL DEFAULT 'EUR',
  `status` ENUM('AUTHORIZED', 'CAPTURED', 'REFUSED', 'REFUNDED', 'CANCELLED') NOT NULL,
  `provider` VARCHAR(100) NOT NULL,
  `provider_payment_id` VARCHAR(191) NOT NULL,
  `created_at` TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  `updated_at` TIMESTAMP NULL DEFAULT NULL,
  PRIMARY KEY (`idpayment`),
  UNIQUE INDEX `uq_provider_payment` (`provider` ASC, `provider_payment_id` ASC) VISIBLE,
  INDEX `idx_payment_reservation` (`reservation_id` ASC) VISIBLE,
  CONSTRAINT `fk_payment_reservation`
    FOREIGN KEY (`reservation_id`)
    REFERENCES `ycyw`.`reservation` (`idreservation`)
    ON DELETE CASCADE
    ON UPDATE RESTRICT)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `ycyw`.`reservation_option`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `ycyw`.`reservation_option` (
  `idoption` BIGINT UNSIGNED NOT NULL AUTO_INCREMENT,
  `code` VARCHAR(50) NOT NULL,
  `label` VARCHAR(150) NOT NULL,
  `daily_price` DECIMAL(10,2) NOT NULL,
  PRIMARY KEY (`idoption`),
  UNIQUE INDEX `uq_res_option_code` (`code` ASC) VISIBLE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `ycyw`.`reservation_option_link`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `ycyw`.`reservation_option_link` (
  `reservation_id` BIGINT UNSIGNED NOT NULL,
  `option_id` BIGINT UNSIGNED NOT NULL,
  `qty` INT UNSIGNED NOT NULL DEFAULT 1,
  PRIMARY KEY (`reservation_id`, `option_id`),
  INDEX `fk_link_option` (`option_id` ASC) VISIBLE,
  CONSTRAINT `fk_link_reservation`
    FOREIGN KEY (`reservation_id`)
    REFERENCES `ycyw`.`reservation` (`idreservation`)
    ON DELETE CASCADE
    ON UPDATE RESTRICT,
  CONSTRAINT `fk_link_option`
    FOREIGN KEY (`option_id`)
    REFERENCES `ycyw`.`reservation_option` (`idoption`)
    ON DELETE RESTRICT
    ON UPDATE RESTRICT)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
